---
title: "section 2"
author: "Masaoud AND Thu"
date: "2/1/2023"
output: pdf_document
---

## Info

- Thu: OH on Tuesday 9-10:30am in SC 316.06. Section on Thursday 9-10am SC 309a
- Masaoud: OH on Tuesday 9-10:30pm in Kirkland Dhall. Section on Friday 12-1pm in Sever 209.

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(ggplot2)
library(dplyr)
```


## Data

```{r}
data("airquality")
```

```{r}
head(airquality)
```
\newpage

# Remove NA:

```{r}
airquality_108 <- airquality %>%
  drop_na(Ozone:Temp)
```


\newpage

# Make a wind chill column

```{r}
# formula:  35.74 + 0.6215 T - 35.75 V^0.16 + 0.4275 T V^0.16
# T = temperature
# V = wind speed
airquality_108 <- airquality %>%
  drop_na(Ozone:Temp) %>%
  mutate(wind_chill = 35.74 + 0.6215 * Temp - 35.75 * Wind^0.16 + 0.4275 * Temp * Wind^0.16)
```

\newpage

# Group by month, average, and make line plot (or whatever plot you want)

```{r}
airquality_108 <- airquality %>%
  drop_na(Ozone, Solar.R, Wind, Temp, Month, Day) %>%
  group_by(Month) %>%
  mutate(wind_chill = 35.74 + 0.6215 * Temp - 35.75 * Wind^0.16 
         + 0.4275 * Temp * Wind^0.16) %>%
  summarize(mean_wind = mean(Wind),
            mean_ozone = mean(Ozone),
            mean_solar = mean(Solar.R),
            mean_temp = mean(Temp), 
            mean_wind_chill = mean(wind_chill)) %>%
  ungroup %>%
  pivot_longer(cols = mean_wind:mean_wind_chill,
               names_to = "type_of_weather",
               values_to = "measure")

airquality_108

```



\newpage

# Animate Line Plot

```{r}
# Type of air quality measure on x axis, monthly average on y axis, animate the change as we move across months
```



